spring:
  application:
    name: digital-wallet

  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migration: true
